import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  Aperture,
  Archive,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  ClipboardSignature,
  Database,
  Download,
  DraftingCompass,
  Euro,
  Factory,
  FileDown,
  FileSearch,
  FileText,
  Flame,
  FolderKanban,
  Gauge,
  Gavel,
  GitPullRequest,
  Hammer,
  HelpCircle,
  History,
  Home,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Network,
  Package,
  Pencil,
  Plug,
  Receipt,
  Repeat2,
  Route,
  Scale,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Target,
  Timer,
  Truck,
  Unlock,
  Upload,
  Users,
  WalletCards,
  Wrench,
  X,
  XCircle,
} from "lucide-react";

export const iconMap = {
  brand: Aperture,
  home: Home,
  marketplace: ShoppingBag,
  how: Route,
  security: Shield,
  about: Info,
  insights: BookOpen,
  legal: Scale,
  contact: Mail,
  requestScope: ClipboardList,
  login: LogIn,
  logout: LogOut,
  external: ArrowUpRight,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  search: Search,
  filter: SlidersHorizontal,
  sort: ArrowUpDown,
  close: X,
  menu: Menu,
  ai: Brain,
  industrial: Factory,
  itot: Network,
  risk: AlertTriangle,
  governance: Gavel,
  architecture: Boxes,
  integration: Plug,
  data: Database,
  realtime: Timer,
  observability: Activity,
  performance: Gauge,
  delivery: Truck,
  resilience: LifeBuoy,
  controls: Lock,
  compliance: BadgeCheck,
  audit: FileSearch,
  design: DraftingCompass,
  build: Hammer,
  operate: Wrench,
  fit: Target,
  outcomes: Sparkles,
  deliverables: Package,
  definitionDone: CheckCircle2,
  process: ListChecks,
  inputs: KeyRound,
  pricing: Euro,
  duration: CalendarClock,
  onsite: MapPin,
  remote: Monitor,
  hybrid: Repeat2,
  faq: HelpCircle,
  dashboard: LayoutDashboard,
  engagements: FolderKanban,
  inquiries: Inbox,
  documents: FileText,
  scopes: ClipboardSignature,
  changeRequests: GitPullRequest,
  billing: Receipt,
  finance: WalletCards,
  notifications: Bell,
  admin: ShieldCheck,
  users: Users,
  orgs: Building2,
  settings: Settings,
  timeline: History,
  edit: Pencil,
  approve: Check,
  reject: XCircle,
  archive: Archive,
  download: Download,
  upload: Upload,
  danger: Flame,
  export: FileDown,
  locked: Lock,
  unlocked: Unlock,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
